/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayOnlineRouteImport } from './routes/play.online'
import { Route as PlayOfflineRouteImport } from './routes/play.offline'
import { Route as PlayOnlineCodeRouteImport } from './routes/play.online.$code'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOnlineRoute = PlayOnlineRouteImport.update({
  id: '/play/online',
  path: '/play/online',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOfflineRoute = PlayOfflineRouteImport.update({
  id: '/play/offline',
  path: '/play/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOnlineCodeRoute = PlayOnlineCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => PlayOnlineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/settings': typeof SettingsRoute
  '/play/offline': typeof PlayOfflineRoute
  '/play/online': typeof PlayOnlineRouteWithChildren
  '/play/online/$code': typeof PlayOnlineCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/settings': typeof SettingsRoute
  '/play/offline': typeof PlayOfflineRoute
  '/play/online': typeof PlayOnlineRouteWithChildren
  '/play/online/$code': typeof PlayOnlineCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/settings': typeof SettingsRoute
  '/play/offline': typeof PlayOfflineRoute
  '/play/online': typeof PlayOnlineRouteWithChildren
  '/play/online/$code': typeof PlayOnlineCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/settings'
    | '/play/offline'
    | '/play/online'
    | '/play/online/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/settings'
    | '/play/offline'
    | '/play/online'
    | '/play/online/$code'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/settings'
    | '/play/offline'
    | '/play/online'
    | '/play/online/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SettingsRoute: typeof SettingsRoute
  PlayOfflineRoute: typeof PlayOfflineRoute
  PlayOnlineRoute: typeof PlayOnlineRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/online': {
      id: '/play/online'
      path: '/play/online'
      fullPath: '/play/online'
      preLoaderRoute: typeof PlayOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/offline': {
      id: '/play/offline'
      path: '/play/offline'
      fullPath: '/play/offline'
      preLoaderRoute: typeof PlayOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/online/$code': {
      id: '/play/online/$code'
      path: '/$code'
      fullPath: '/play/online/$code'
      preLoaderRoute: typeof PlayOnlineCodeRouteImport
      parentRoute: typeof PlayOnlineRoute
    }
  }
}

interface PlayOnlineRouteChildren {
  PlayOnlineCodeRoute: typeof PlayOnlineCodeRoute
}

const PlayOnlineRouteChildren: PlayOnlineRouteChildren = {
  PlayOnlineCodeRoute: PlayOnlineCodeRoute,
}

const PlayOnlineRouteWithChildren = PlayOnlineRoute._addFileChildren(
  PlayOnlineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  SettingsRoute: SettingsRoute,
  PlayOfflineRoute: PlayOfflineRoute,
  PlayOnlineRoute: PlayOnlineRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
