/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayOfflineRouteImport } from './routes/play.offline'
import { Route as PlayOnlineIndexRouteImport } from './routes/play.online.index'
import { Route as PlayOnlineCodeRouteImport } from './routes/play.online.$code'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOfflineRoute = PlayOfflineRouteImport.update({
  id: '/play/offline',
  path: '/play/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOnlineIndexRoute = PlayOnlineIndexRouteImport.update({
  id: '/play/online/',
  path: '/play/online/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOnlineCodeRoute = PlayOnlineCodeRouteImport.update({
  id: '/play/online/$code',
  path: '/play/online/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/instructions': typeof InstructionsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/settings': typeof SettingsRoute
  '/play/offline': typeof PlayOfflineRoute
  '/play/online/$code': typeof PlayOnlineCodeRoute
  '/play/online/': typeof PlayOnlineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/instructions': typeof InstructionsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/settings': typeof SettingsRoute
  '/play/offline': typeof PlayOfflineRoute
  '/play/online/$code': typeof PlayOnlineCodeRoute
  '/play/online': typeof PlayOnlineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/instructions': typeof InstructionsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/settings': typeof SettingsRoute
  '/play/offline': typeof PlayOfflineRoute
  '/play/online/$code': typeof PlayOnlineCodeRoute
  '/play/online/': typeof PlayOnlineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/auth'
    | '/friends'
    | '/instructions'
    | '/leaderboard'
    | '/settings'
    | '/play/offline'
    | '/play/online/$code'
    | '/play/online/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/auth'
    | '/friends'
    | '/instructions'
    | '/leaderboard'
    | '/settings'
    | '/play/offline'
    | '/play/online/$code'
    | '/play/online'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/auth'
    | '/friends'
    | '/instructions'
    | '/leaderboard'
    | '/settings'
    | '/play/offline'
    | '/play/online/$code'
    | '/play/online/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  FriendsRoute: typeof FriendsRoute
  InstructionsRoute: typeof InstructionsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SettingsRoute: typeof SettingsRoute
  PlayOfflineRoute: typeof PlayOfflineRoute
  PlayOnlineCodeRoute: typeof PlayOnlineCodeRoute
  PlayOnlineIndexRoute: typeof PlayOnlineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/offline': {
      id: '/play/offline'
      path: '/play/offline'
      fullPath: '/play/offline'
      preLoaderRoute: typeof PlayOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/online/': {
      id: '/play/online/'
      path: '/play/online'
      fullPath: '/play/online/'
      preLoaderRoute: typeof PlayOnlineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/online/$code': {
      id: '/play/online/$code'
      path: '/play/online/$code'
      fullPath: '/play/online/$code'
      preLoaderRoute: typeof PlayOnlineCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  FriendsRoute: FriendsRoute,
  InstructionsRoute: InstructionsRoute,
  LeaderboardRoute: LeaderboardRoute,
  SettingsRoute: SettingsRoute,
  PlayOfflineRoute: PlayOfflineRoute,
  PlayOnlineCodeRoute: PlayOnlineCodeRoute,
  PlayOnlineIndexRoute: PlayOnlineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
